########################################
# Docker Compose File for UTD Roboboat #
########################################
#
# Usage:
# - To build the images:
#     `docker compose build`
# - To start up a specific service detatched:
#     `docker compose up -d <service_name>`
# - To open an attach to a running service:
#     `docker compose attach <service_name>`
#
##########################################################

services:
  development:
    image: utdrobosub/roboboat-2025:development
    build:
      context: .
      dockerfile: Docker/Dockerfile
      target: development
      platforms:
        - 'linux/amd64'
        - 'linux/arm64'
    # Interactive shell
    tty: True
    stdin_open: True
    privileged: True
    # Networking and IPC for ROS 2
    network_mode: host
    ipc: host
    # NVidia Runtime
    # runtime: nvidia
    environment:
      # Needed to define a TurtleBot3 model type
      - TURTLEBOT3_MODEL=burger
      # Allows graphical programs in the container.
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
    # Devices:
    device_cgroup_rules:
      - "c 189:* rmw"
    volumes:
      # Allows graphical programs in the container.
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
      # Access to all Host Devices
      - /dev:/dev
      # Share config / src Directories
      - ./.config:/root/.config
      - ./src/roboboat2025_ros2:/root/roboboat_ws/src/roboboat2025_ros2
  sim:
    extends: development
    tty: False
    stdin_open: False
    command: ros2 launch vrx_gz competition.launch.py
  healthcheck:
    extends: development
    tty: False
    stdin_open: False
    command: ros2 doctor
  # release:
  #   image: utdrobosub/roboboat-2025:release
  #   build:
  #     context: .
  #     dockerfile: Docker/Dockerfile
  #     target: release
  #     platforms:
  #       - 'linux/amd64'
  #       - 'linux/arm64'
  #   # Interactive shell
  #   tty: True
  #   stdin_open: True
  #   privileged: True
  #   # Networking and IPC for ROS 2
  #   network_mode: host
  #   ipc: host
  #   # NVidia Runtime
  #   runtime: nvidia
  #   environment:
  #     # Needed to define a TurtleBot3 model type
  #     - TURTLEBOT3_MODEL=burger
  #     # Allows graphical programs in the container.
  #     - DISPLAY=${DISPLAY}
  #     - QT_X11_NO_MITSHM=1
  #     - NVIDIA_DRIVER_CAPABILITIES=all
  #   # Devices:
  #   device_cgroup_rules:
  #     - "c 189:* rmw"
  #   volumes:
  #     # Access to all Host Devices
  #     - /dev:/dev
